# Generated by Django 4.0.6 on 2022-07-13 16:16
import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("countries", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="country",
            name="ogc_fid",
        ),
        migrations.AlterField(
            model_name="country",
            name="geom",
            field=django.contrib.gis.db.models.fields.MultiPolygonField(
                srid=4326),
        ),
    ]
