# Generated by Django 4.0.6 on 2022-07-12 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0002_alter_country_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'managed': False, 'verbose_name': 'polygon', 'verbose_name_plural': 'polygons'},
        ),
    ]
