services:
  db:
    image: postgis/postgis:13-3.2-alpine
    container_name: spatial_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=spatial_data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  fastapi:
    container_name: fastapi_app
    build: ./FastAPI/src
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./FastAPI/src/:/usr/src/app/
    ports:
      - 8002:8000
    environment:
      - DB_NAME=spatial_data
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_PORT=5432
      - DB_HOST=db
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
