version: "3.8"
services:
  web:
    container_name: web_app
    build: ./src
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./src/:/usr/src/app/
    ports:
      - 8002:8000
  db:
    container_name: database
    image: postgis/postgis:13-3.2-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=priyansh
      - POSTGRES_PASSWORD=priyanshbordia
      - POSTGRES_DB=spatial_data

volumes:
  postgres_data:

  # python3:
  #   restart: always
  #   build: .
  #   container_name: "spatial-data-container"
  #   working_dir: "/"
  #   tty: true
